features:
- answered_correctly_avg_u
- answered_correctly_avg_u_class1000
- answered_correctly_rolling3
- answered_correctly_rolling3_div_elapsed_from_prior
- answered_correctly_rolling5
- answered_correctly_rolling5_div_elapsed_from_prior
- answered_correctly_rolling7
- answered_correctly_rolling7_div_elapsed_from_prior
- answered_correctly_sum_u
- answered_correctly_sum_u_class1000
- attempt_c
- attempt_c_class1000
- content_id
- content_id_diff_abs
- content_id_tsne_0
- content_id_tsne_1
- content_type_id
- count_u
- count_u_class1000
- equal_prior_question_flag
- equal_prior_question_flag_class1000
- order_content_id_by_task_container_id
- order_content_id_div_max_by_task_container_id
- part
- prior_question_elapsed_time
- prior_question_elapsed_time_diff_mean_by_content_id
- prior_question_elapsed_time_diff_mean_by_content_id_bin
- prior_question_elapsed_time_diff_mean_by_user_id_and_part
- prior_question_elapsed_time_diff_median_by_content_id
- prior_question_elapsed_time_diff_median_by_content_id_bin
- prior_question_elapsed_time_diff_median_by_user_id_and_part
- prior_question_elapsed_time_div_mean_by_content_id
- prior_question_elapsed_time_div_mean_by_content_id_bin
- prior_question_elapsed_time_div_mean_by_user_id_and_part
- prior_question_elapsed_time_div_median_by_content_id
- prior_question_elapsed_time_div_median_by_content_id_bin
- prior_question_elapsed_time_div_median_by_user_id_and_part
- prior_question_elapsed_time_max
- prior_question_elapsed_time_max_by_content_id
- prior_question_elapsed_time_max_by_content_id_bin
- prior_question_elapsed_time_max_by_user_id_and_part
- prior_question_elapsed_time_mean
- prior_question_elapsed_time_mean_by_content_id
- prior_question_elapsed_time_mean_by_content_id_bin
- prior_question_elapsed_time_mean_by_user_id_and_part
- prior_question_elapsed_time_median
- prior_question_elapsed_time_median_by_content_id
- prior_question_elapsed_time_median_by_content_id_bin
- prior_question_elapsed_time_median_by_user_id_and_part
- prior_question_elapsed_time_min
- prior_question_elapsed_time_min_by_content_id
- prior_question_elapsed_time_min_by_content_id_bin
- prior_question_elapsed_time_min_by_user_id_and_part
- prior_question_elapsed_time_std
- prior_question_elapsed_time_std_by_content_id
- prior_question_elapsed_time_std_by_content_id_bin
- prior_question_elapsed_time_std_by_user_id_and_part
- prior_question_had_explanation
- seq2dec_w3
- seq2dec_w5
- seq2dec_w7
- tag_w2v_max
- tag_w2v_mean
- tag_w2v_median
- tag_w2v_min
- tag_w2v_std
- task_container_id
- task_container_id_diff_abs
- te_content_id_and_attempt_c_by_answered_correctly
- te_content_id_by_answered_correctly
- te_content_id_next_by_answered_correctly
- te_content_id_prior_by_answered_correctly
- te_part_by_answered_correctly
- te_tag_by_answered_correctly
- te_type_of_by_answered_correctly
- timestamp
- timestamp_diff1
- timestamp_diff1_div_timestamp_diff2
- timestamp_diff1_div_timestamp_diff3
- timestamp_diff1_div_timestamp_diff4
- timestamp_diff1_div_timestamp_diff5
- timestamp_diff2
- timestamp_diff2_div_timestamp_diff3
- timestamp_diff2_div_timestamp_diff4
- timestamp_diff2_div_timestamp_diff5
- timestamp_diff3
- timestamp_diff3_div_timestamp_diff4
- timestamp_diff3_div_timestamp_diff5
- timestamp_diff4
- timestamp_diff4_div_timestamp_diff5
- timestamp_diff5
- timestamp_lag_diff_mean_each_user
- timestamp_lag_diff_median_each_user
- timestamp_lag_diff_rolling3_mean_each_user
- timestamp_lag_diff_rolling3_median_each_user
- timestamp_lag_diff_rolling5_mean_each_user
- timestamp_lag_diff_rolling5_median_each_user
- timestamp_lag_diff_rolling7_mean_each_user
- timestamp_lag_diff_rolling7_median_each_user
- timestamp_lag_div_mean_each_user
- timestamp_lag_div_median_each_user
- timestamp_lag_mean
- timestamp_lag_median
- user_id
