features:
- answered_correctly_avg_u
- answered_correctly_avg_u_class1000
- answered_correctly_rolling3
- answered_correctly_rolling5
- answered_correctly_rolling7
- answered_correctly_sum_u
- answered_correctly_sum_u_class1000
- attempt_c
- attempt_c_class1000
- content_id
- content_id_tsne_0
- content_id_tsne_1
- content_type_id
- count_u
- count_u_class1000
- equal_prior_question_flag
- equal_prior_question_flag_class1000
- part
- prior_question_elapsed_time
- prior_question_elapsed_time_div_mean_by_content_id_bin
- prior_question_elapsed_time_div_mean_by_user_id_and_part
- prior_question_elapsed_time_div_median_by_content_id_bin
- prior_question_elapsed_time_div_median_by_user_id_and_part
- prior_question_elapsed_time_max
- prior_question_elapsed_time_mean
- prior_question_elapsed_time_median
- prior_question_elapsed_time_min
- prior_question_elapsed_time_std
- prior_question_had_explanation
- tag_w2v_max
- tag_w2v_mean
- tag_w2v_median
- tag_w2v_min
- tag_w2v_std
- task_container_id
- te_content_id_and_attempt_c_by_answered_correctly
- te_content_id_by_answered_correctly
- te_part_by_answered_correctly
- te_tag_by_answered_correctly
- te_type_of_by_answered_correctly
- timestamp
- user_id
