features:
- answered_correctly_avg_u
- answered_correctly_sum_u
- attempt_c
- content_id
- content_id_tsne_0
- content_id_tsne_1
- content_type_id
- count_u
- equal_prior_question_flag
- part
- prior_question_elapsed_time
- prior_question_had_explanation
- task_container_id
- te_content_id_by_answered_correctly
- te_part_by_answered_correctly
- te_tag_by_answered_correctly
- te_type_of_by_answered_correctly
- timestamp
- user_id
