features:
  - dropped___answered_correctly_avg_u
  - dropped___answered_correctly_sum_u
  - dropped___attempt_c
  - dropped___count_u
  - dropped___prior_question_elapsed_time
  - dropped___task_container_id
  - dropped___te_content_id_by_answered_correctly
  - dropped___part
  - dropped___te_content_id_and_attempt_c_by_answered_correctly
  - dropped___content_id_tsne_0
  - dropped___content_id_tsne_1
  - dropped___tag_w2v_max
  - dropped___tag_w2v_mean
  - dropped___tag_w2v_median
  - dropped___tag_w2v_min
  - dropped___prior_question_elapsed_time_mean_by_content_id
  - dropped___prior_question_elapsed_time_median_by_content_id
  - dropped___prior_question_elapsed_time_std_by_content_id
  - dropped___timestamp_diff1
  - dropped___timestamp_diff2
  - dropped___timestamp_diff3
  - dropped___timestamp_diff4
  - dropped___timestamp_diff5
  - dropped___seq2dec_w3
  - dropped___seq2dec_w5
  - dropped___seq2dec_w7
  - dropped___timestamp_lag_diff_median_each_user
  - dropped___timestamp_lag_div_median_each_user
  - dropped___timestamp_lag_median
  - dropped___timestamp_lag_diff_rolling3_mean_each_user
  - dropped___timestamp_lag_diff_rolling3_median_each_user
  - dropped___timestamp_lag_diff_rolling5_mean_each_user
  - dropped___timestamp_lag_diff_rolling5_median_each_user
  - dropped___timestamp_lag_diff_rolling7_mean_each_user
  - dropped___timestamp_lag_diff_rolling7_median_each_user
  - dropped___te_content_id_prior_by_answered_correctly
  - dropped___content_id_diff_abs
  - dropped___task_container_id_diff_abs
  - dropped___timestamp_lag_shift1