features:
  - answered_correctly_avg_u
  - answered_correctly_sum_u
  - attempt_c
  - count_u
  - prior_question_elapsed_time
  - task_container_id
  - te_content_id_by_answered_correctly
  - part
  - te_part_by_answered_correctly
  - te_content_id_and_attempt_c_by_answered_correctly
  - content_id_tsne_0
  - content_id_tsne_1
  - tag_w2v_max
  - tag_w2v_mean
  - tag_w2v_median
  - tag_w2v_min
  - prior_question_elapsed_time_div_mean_by_user_id_and_part
  - prior_question_elapsed_time_div_median_by_content_id_bin
  - prior_question_elapsed_time_div_median_by_user_id_and_part
  - prior_question_elapsed_time_mean
  - prior_question_elapsed_time_median
  - prior_question_elapsed_time_std
  - answered_correctly_rolling3
  - timestamp_diff1
  - timestamp_diff2
  - timestamp_diff3
  - timestamp_diff4
  - timestamp_diff5
  - answered_correctly_rolling3_div_elapsed_from_prior
  - seq2dec_w3
  - seq2dec_w5
  - seq2dec_w7
  - timestamp_lag_diff_mean_each_user
  - timestamp_lag_div_mean_each_user
  - timestamp_lag_mean