features:
  - content_id__answered_correctly_sm5
  - u_prev_difftime
  - content_id__weighted_answered_correctly_sm5
  - u_hist_ques_ansed
  - u_hist_part_num_corr_rate
  - content_id__std
  - u_corr_rate
  - u_prev_lag_diff_time
  - u_prev_et_diff_time
  - timestamp_lag_diff_median_each_user
  - u_latest100_corr_rate
  - u_corr_rate_smooth
  - u_prev_diff_lag_time
  - u_prev_difftime_incorr
  - timestamp_lag_div_median_each_user
  - content_id__question_elapsed_time_sm5
  - u_part_6_corr_rate
  - content_id__weighted_answered_correctly_sm5_repeat
  - u_hade_div_corr_cnt
  - u_hist_ques_num
  - content_id_diff_abs
  - seq2dec_w7
  - task_container_id_diff_abs
  - u_latest10_corr_rate
  - corr_gsvd_3
  - u_part_1_cnt
  - u_latest30_corr_rate
  - part__svd_0
  - content_id__weighted_score_sm5_repeat
  - u_hist_tag_corr_rate_min
  - content_id__entropy__user_answer
  - u_part_7_corr_rate
  - u_part_5_corr_rate
  - seq2dec_w3
  - timestamp_lag_median
  - content_order_median
  - te_content_id_prior_by_answered_correctly
  - u_part_2_cnt
  - seq2dec_w5
  - u_part_5_cnt
  - content_id__svd_4
  - content_id__svd_3
  - u_cnt_in_session_short_density
  - content_id_tsne_1
  - content_id__svd_2
  - u_part_4_corr_rate
  - u_hist_part_num
  - timestamp
  - part__svd_1
  - u_part_3_corr_rate