features:
  - answered_correctly_avg_u
  - answered_correctly_sum_u
  - attempt_c_class1000
  - content_id
  - content_type_id
  - count_u
  - equal_prior_question_flag_class1000
  - prior_question_elapsed_time
  - prior_question_had_explanation
  - task_container_id
  - timestamp
  - user_id
  - te_content_id_by_answered_correctly
  - part
  - te_part_by_answered_correctly
  - te_tag_by_answered_correctly
  - te_type_of_by_answered_correctly
  - content_id_tsne_0
  - content_id_tsne_1
  - tag_w2v_max
  - tag_w2v_mean
  - tag_w2v_median
  - tag_w2v_min
  - tag_w2v_std