line:
    token: KW0J7oCXjxkqGtiuZrn79ahpmWOgzc8M12DFbwGyTzW
notion:
    url: https://www.notion.so/e48a5ce616634992a9613d62515e87f5?v=4408f4ab983a4d848abbd11fc15ed81f
slack:
    url: https://hooks.slack.com/services/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