common:
    seed: &seed 2020
    metrics:
        name: auc
        params: {}
    drop:
      - lecture_idx
    kaggle:
        data: False
        notebook: False

data:
    loader:
        train:
            data_type: train
            reduce: False
    sampling: True
    features:
        name: custom_003
        cat_features:
        oof:
            name:
    target:
        name: &target_name answered_correctly
        convert_type:
        reconvert_type:
    adversarial_validation: False

model:
    name: catboost
    task_type: binary
    params:
        loss_function: Logloss
        eval_metric: AUC
        learning_rate: 0.3
        iterations: 10_000
        depth: 7
        random_seed: *seed
        task_type: GPU
    verbose_eval: 100
    early_stopping_rounds: 100
    imp_type: total_gain
    feval: