common:
    seed: &seed 2020
    metrics:
        name: auc
        params: {}
    drop:
    debug: False
    kaggle:
        data: False
        notebook: False

model:
    backbone: mlp2
    n_classes: &class 1
    epochs: &epochs 30
    params:
        dim_input: &dim_input 112
        e_dim: 128
    multi_gpu: True
    head:
      drop1:
        name: Dropout
        params:
          p: 0.
      linear1:
        name: Linear
        params:
          in_features: 239
          out_features: &hidden1 1000
        weight_norm: False
      act1:
        name: ReLU
        params: {}
      drop2:
        name: Dropout
        params:
          p: 0.
      linear2:
        name: Linear
        params:
          in_features: *hidden1
          out_features: &hidden2 476
        weight_norm: False
      act2:
        name: ReLU
        params: {}
      drop3:
        name: Dropout
        params:
          p: 0.
      linear3:
        name: Linear
        params:
          in_features: *hidden2
          out_features: *class
        weight_norm: False

data:
    features:
        name: custom_514
        embedding_cols:
          - content_id
    train:
        dataset_type: &dataset CustomMlpDataset2
        is_train: True
        loader:
            shuffle: True
            batch_size: 4096
            num_workers: 4
        transforms:
    valid:
        dataset_type: *dataset
        is_train: False
        loader:
            shuffle: False
            batch_size: 2048
            num_workers: 4
        transforms:
    test:
        dataset_type: *dataset
        is_train: False
        loader:
            shuffle: False
            batch_size: 4096
            num_workers: 4
        transforms:

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 30