common:
    seed: &seed 2020
    metrics:
        name: auc
        params: {}
    drop:
    debug: False
    kaggle:
        data: False
        notebook: False

model:
    backbone: tabnet
    n_classes: &class 1
    epochs: &epochs 30
    params:
        input_dim: 112
        output_dim: *class
        n_d: &n_d 31
        n_a: 14
        n_steps: 1
        gamma: 1.3
        cat_idxs: []
        cat_dims: []
        cat_emb_dim: 1
        n_independent: 2
        n_shared: 2
        virtual_batch_size: 128
        momentum: 0.02
        mask_type: entmax
    multi_gpu: True
    head:
        linear:
            name: Linear
            params:
                in_features: *n_d
                out_features: *class

data:
    features:
      name: custom_514
    train:
        dataset_type: &dataset CustomMlpDataset
        is_train: True
        loader:
            shuffle: True
            batch_size: 8192
            num_workers: 4
        transforms:
    valid:
        dataset_type: *dataset
        is_train: True
        loader:
            shuffle: False
            batch_size: 2048
            num_workers: 4
        transforms:
    test:
        dataset_type: *dataset
        is_train: False
        loader:
            shuffle: False
            batch_size: 8192
            num_workers: 4
        transforms:

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 30