common:
    seed: &seed 2020
    metrics:
        name: auc
        params: {}
    drop:
      - lecture_idx
    debug: False
    kaggle:
        data: False
        notebook: False

model:
    backbone: transformer_public
    n_classes: &class 1
    epochs: &epochs 30
    params:
        n_skill: &n_skill 13_523
        max_seq: &max_seq 120
    multi_gpu: False
    head:

data:
    train:
        dataset_type: CustomTrainDataset2
        is_train: True
        params:
            n_skill: *n_skill
            max_seq: *max_seq
        loader:
            shuffle: True
            batch_size: 2048
            num_workers: 4
        transforms:
    valid:
        dataset_type: CustomTestDataset
        is_train: False
        params:
            n_skill: *n_skill
            max_seq: *max_seq
        loader:
            shuffle: False
            batch_size: 1024
            num_workers: 4
        transforms:
    test:
        dataset_type: CustomTestDataset
        is_train: False
        params:
            n_skill: *n_skill
            max_seq: *max_seq
        loader:
            shuffle: False
            batch_size: 2048
            num_workers: 4
        transforms:

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 30