common:
    seed: &seed 2020
    metrics:
        name: auc
        params: {}
    drop:
      - lecture_idx
    debug: True
    kaggle:
        data: False
        notebook: False

model:
    backbone: transformer_v1
    n_classes: &class 1
    epochs: &epochs 10
    params:
        dim_input: 8   # historyの入力
        dim_enc: 16   # transformerの入力
        dim_fc: 16   # 最後の全結合層の中間
        dim_output: 1
        dim_cur_input: 5   # currentの次元
        ff_inner: 10
        ff_slope: 0.2
        head: 4
        dropout1: 0.20
        dropout2: 0.20
        dropout3: 0.20
    multi_gpu: False
    head:

data:
    train:
        dataset_type: &dataset CustomDataset
        is_train: True
        loader:
            shuffle: True
            batch_size: 4096
            num_workers: 4
        transforms:
    valid:
        dataset_type: *dataset
        is_train: True
        loader:
            shuffle: False
            batch_size: 1024
            num_workers: 4
        transforms:
    test:
        dataset_type: *dataset
        is_train: False
        loader:
            shuffle: False
            batch_size: 4096
            num_workers: 4
        transforms:

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 10